### ISSUE TITLE
O .vscode não está no .gitignore

### ISSUE THREAD

**Issue by yotta0** [denyxaax15/new-lampions#2]
- o .vscode é um arquivo de configuração do Visual Studio Code, que não deve ir para versionamento
- O arquivo .gitignore é um arquivo em que você coloca os arquivos que não podem ir para o git
- para resolver isso basta criar um arquivo com o nome .gitignore na raiz do projeto
e dentro do arquivo escrever a seguinte linha:

```
.vscode

```

**Comment by oliveira419** [comment]
Entendido
